export const translations = {
  pt: {
    dashboard: "Painel de Controlo",
    map: "Mapa de Inteligência",
    community: "Feed Comunitário",
    myReports: "Meus Registos",
    settings: "Definições",
    logout: "Sair",
    logout_confirm_title: "Terminar Sessão?",
    logout_confirm_msg: "Tens a certeza que desejas sair do sistema de vigilância?",
    confirm_yes: "Sim, Sair",
    confirm_no: "Cancelar",
    login: "Entrar com Google",
    welcome: "Bem-vindo, Agente",
    stats_total: "Total de Registos",
    stats_impact: "Impacto Social",
    stats_score: "Cidadania",
    report_incident: "Reportar Incidente",
    description_placeholder: "O que está a acontecer? Descreva o problema...",
    add_photo: "Adicionar Foto",
    change_photo: "Alterar Foto",
    location_set: "Localização Definida",
    select_location: "Selecionar no Mapa",
    submit_report: "Enviar Relatório",
    processing: "A processar...",
    location_required: "Por favor, selecione um local no mapa para enviar",
    settings_account: "Perfil do Agente",
    settings_system: "Preferências do Sistema",
    settings_voice: "Alertas de Voz",
    settings_theme: "Tema Visual",
    settings_lang: "Idioma do Sistema",
    settings_personalize: "Personalização",
    username_label: "Nome de Agente",
    bio_label: "Biografia/Status",
    save_changes: "Guardar Alterações",
    gdpr_title: "Privacidade e RGPD",
    gdpr_desc: "Gerencie os seus dados pessoais e de acordo com as normas europeias de proteção de dados.",
    gdpr_export: "Exportar Meus Dados (JSON)",
    gdpr_delete: "Eliminar Minha Conta e Dados",
    gdpr_delete_warn: "Esta ação é irreversível.",
    severity_label: "Gravidade",
    ai_analysis_label: "Análise da IA",
    pdf_report_btn: "RELATÓRIO PDF",
    level_label: "Nível",
    activity_pulse: "Pulso de Atividade",
    recent_milestones: "Conquistas Recentes",
    select_target_msg: "SELECIONE O LOCAL DO INCIDENTE NO MAPA",
    voice_alert_text: "Atenção. Novo incidente de {category} com gravidade {severity}. Resumo: {summary}.",
    navigation: "Navegação",
    start_point: "Ponto de Partida",
    end_point: "Destino",
    get_directions: "Traçar Rota",
    clear_route: "Limpar Rota",
    my_location: "Minha Localização",
    route_info: "Informação da Viagem",
    show_radars: "Exibir Radares",
    radar_limit: "Limite de Velocidade",
    radar_type: "Tipo de Radar",
    radar_fixed: "Fixo",
    radar_alert_voice: "Atenção. Radar fixo a quinhentos metros. Limite de velocidade: {limit} quilómetros por hora.",
    ai_tools: "Ferramentas Pro",
    legal_assistant: "Defesa Jurídica",
    generate_defense: "Gerar Requerimento",
    vigilante_chat: "Conversar com Vigilante",
    chat_placeholder: "Pergunte algo sobre trânsito ou multas...",
    generating: "A gerar documento...",
    defense_ready: "Requerimento Gerado",
    ask_vigilante: "Perguntar ao Vigilante",
    upload_pdf: "Anexar Notificação (PDF)",
    pdf_size_error: "O ficheiro PDF é demasiado grande. Máximo 500KB.",
    pdf_type_error: "Apenas ficheiros PDF são permitidos.",
    file_attached: "Documento anexado: {name}"
  },
  en: {
    dashboard: "Dashboard",
    map: "Intelligence Map",
    community: "Community Feed",
    myReports: "My Reports",
    settings: "Settings",
    logout: "Sign Out",
    logout_confirm_title: "Sign Out?",
    logout_confirm_msg: "Are you sure you want to leave the surveillance system?",
    confirm_yes: "Yes, Logout",
    confirm_no: "Cancel",
    login: "Login with Google",
    welcome: "Welcome, Agent",
    stats_total: "Total Reports",
    stats_impact: "Social Impact",
    stats_score: "Citizenship Score",
    report_incident: "Report Incident",
    description_placeholder: "What's happening? Describe the issue...",
    add_photo: "Add Photo",
    change_photo: "Change Photo",
    location_set: "Location Set",
    select_location: "Select on Map",
    submit_report: "Submit Report",
    processing: "Processing...",
    location_required: "Please select a location on the map to submit",
    settings_account: "Agent Profile",
    settings_system: "System Preferences",
    settings_voice: "Voice Alerts",
    settings_theme: "Visual Theme",
    settings_lang: "System Language",
    settings_personalize: "Personalization",
    username_label: "Agent Name",
    bio_label: "Bio/Status",
    save_changes: "Save Changes",
    gdpr_title: "Privacy & GDPR",
    gdpr_desc: "Manage your personal data in accordance with European data protection standards.",
    gdpr_export: "Export My Data (JSON)",
    gdpr_delete: "Delete Account & Data",
    gdpr_delete_warn: "This action is permanent.",
    severity_label: "Severity",
    ai_analysis_label: "AI Analysis",
    pdf_report_btn: "PDF REPORT",
    level_label: "Level",
    activity_pulse: "Activity Pulse",
    recent_milestones: "Recent Milestones",
    select_target_msg: "SELECT INCIDENT LOCATION ON MAP",
    voice_alert_text: "Attention. New {category} incident reported with {severity} severity. Summary: {summary}.",
    navigation: "Navigation",
    start_point: "Start Point",
    end_point: "Destination",
    get_directions: "Get Directions",
    clear_route: "Clear Route",
    my_location: "My Location",
    route_info: "Trip Info",
    show_radars: "Show Radars",
    radar_limit: "Speed Limit",
    radar_type: "Radar Type",
    radar_fixed: "Fixed",
    radar_alert_voice: "Attention. Fixed speed camera five hundred meters ahead. Speed limit: {limit} kilometers per hour.",
    ai_tools: "Pro Tools",
    legal_assistant: "Legal Defense",
    generate_defense: "Generate Requirement",
    vigilante_chat: "Chat with Vigilante",
    chat_placeholder: "Ask something about traffic or fines...",
    generating: "Generating document...",
    defense_ready: "Requirement Generated",
    ask_vigilante: "Ask Vigilante",
    upload_pdf: "Attach Notice (PDF)",
    pdf_size_error: "PDF file is too large. Maximum 500KB.",
    pdf_type_error: "Only PDF files are allowed.",
    file_attached: "Document attached: {name}"
  },
  es: {
    dashboard: "Panel de Control",
    map: "Mapa de Inteligencia",
    community: "Feed Comunitario",
    myReports: "Mis Informes",
    settings: "Configuración",
    logout: "Cerrar sesión",
    logout_confirm_title: "¿Cerrar Sesión?",
    logout_confirm_msg: "¿Estás seguro de que deseas salir del sistema de vigilancia?",
    confirm_yes: "Sí, Salir",
    confirm_no: "Cancelar",
    login: "Entrar con Google",
    welcome: "Bienvenido, Agente",
    stats_total: "Total de Informes",
    stats_impact: "Impacto Social",
    stats_score: "Puntaje Ciudadano",
    report_incident: "Reportar Incidente",
    description_placeholder: "¿Qué está pasando? Describa el problema...",
    add_photo: "Añadir Foto",
    change_photo: "Cambiar Foto",
    location_set: "Ubicación Definida",
    select_location: "Seleccionar en Mapa",
    submit_report: "Enviar Informe",
    processing: "Procesando...",
    location_required: "Por favor, seleccione un lugar en el mapa para enviar",
    settings_account: "Perfil de Agente",
    settings_system: "Preferencias del Sistema",
    settings_voice: "Alertas de Voz",
    settings_theme: "Tema Visual",
    settings_lang: "Idioma del Sistema",
    settings_personalize: "Personalización",
    username_label: "Nombre de Agente",
    bio_label: "Biografía/Estado",
    save_changes: "Guardar Cambios",
    gdpr_title: "Privacidad y RGPD",
    gdpr_desc: "Gestione sus datos personales de acuerdo con las normas europeas de protección de datos.",
    gdpr_export: "Exportar Mis Datos (JSON)",
    gdpr_delete: "Eliminar Mi Cuenta y Datos",
    gdpr_delete_warn: "Esta acción es irreversible.",
    severity_label: "Gravedad",
    ai_analysis_label: "Análisis de IA",
    pdf_report_btn: "INFORME PDF",
    level_label: "Nivel",
    activity_pulse: "Pulso de Atividade",
    recent_milestones: "Logros Recientes",
    select_target_msg: "SELECIONE EL LUGAR DEL INCIDENTE EN EL MAPA",
    voice_alert_text: "Atención. Nuevo incidente de {category} con gravedad {severity}. Resumen: {summary}.",
    navigation: "Navegação",
    start_point: "Punto de Partida",
    end_point: "Destino",
    get_directions: "Trazar Ruta",
    clear_route: "Limpiar Ruta",
    my_location: "Mi Ubicación",
    route_info: "Info del Viaje",
    show_radars: "Mostrar Radares",
    radar_limit: "Límite de Velocidad",
    radar_type: "Tipo de Radar",
    radar_fixed: "Fijo",
    radar_alert_voice: "Atención. Radar fijo a quinientos metros. Límite de velocidad: {limit} kilómetros por hora.",
    ai_tools: "Herramientas Pro",
    legal_assistant: "Defensa Legal",
    generate_defense: "Generar Requerimiento",
    vigilante_chat: "Hablar con Vigilante",
    chat_placeholder: "Pregunta algo sobre tráfico o multas...",
    generating: "Generando documento...",
    defense_ready: "Requerimento Generado",
    ask_vigilante: "Preguntar al Vigilante",
    upload_pdf: "Adjuntar Notificación (PDF)",
    pdf_size_error: "El archivo PDF es demasiado grande. Máximo 500KB.",
    pdf_type_error: "Solo se permitem archivos PDF.",
    file_attached: "Documento adjunto: {name}"
  },
  fr: {
    dashboard: "Tableau de Bord",
    map: "Carte d'Intelligence",
    community: "Fil Communautaire",
    myReports: "Mes Rapports",
    settings: "Paramètres",
    logout: "Déconnexion",
    logout_confirm_title: "Déconnexion ?",
    logout_confirm_msg: "Êtes-vous sûr de vouloir quitter le système de surveillance ?",
    confirm_yes: "Oui, Sortir",
    confirm_no: "Annuler",
    login: "Connexion Google",
    welcome: "Bienvenue, Agent",
    stats_total: "Total des Rapports",
    stats_impact: "Impact Social",
    stats_score: "Score Citoyen",
    report_incident: "Signaler un Incident",
    description_placeholder: "Que se passe-t-il? Décrivez le problème...",
    add_photo: "Ajouter Photo",
    change_photo: "Changer Photo",
    location_set: "Position Définie",
    select_location: "Choisir sur la Carte",
    submit_report: "Envoyer le Rapport",
    processing: "Traitement...",
    location_required: "Veuillez choisir un lieu sur la carte pour envoyer",
    settings_account: "Profil de l'Agent",
    settings_system: "Préférences Système",
    settings_voice: "Alertes Vocales",
    settings_theme: "Thème Visuel",
    settings_lang: "Langue du Système",
    settings_personalize: "Personnalisation",
    username_label: "Nom de l'Agent",
    bio_label: "Bio/Statut",
    save_changes: "Enregistrer",
    gdpr_title: "Confidentialité & RGPD",
    gdpr_desc: "Gérez vos données personnelles conformément aux normes européennes de protection des données.",
    gdpr_export: "Exporter Mes Données (JSON)",
    gdpr_delete: "Supprimer Mon Compte et Données",
    gdpr_delete_warn: "Cette action est irréversible.",
    severity_label: "Gravité",
    ai_analysis_label: "Analyse IA",
    pdf_report_btn: "RAPPORT PDF",
    level_label: "Niveau",
    activity_pulse: "Pouls d'Activité",
    recent_milestones: "Succès Récents",
    select_target_msg: "SÉLECTIONNEZ LE LIEU DE L'INCIDENT SUR LA CARTE",
    voice_alert_text: "Attention. Nouvel incident de {category} avec une gravité {severity}. Résumé: {summary}.",
    navigation: "Navigation",
    start_point: "Point de Départ",
    end_point: "Destination",
    get_directions: "Tracer l'Itinéraire",
    clear_route: "Effacer l'Itinéraire",
    my_location: "Ma Position",
    route_info: "Infos Voyage",
    show_radars: "Afficher les Radars",
    radar_limit: "Limite de Vitesse",
    radar_type: "Type de Radar",
    radar_fixed: "Fixe",
    radar_alert_voice: "Attention. Radar fixe à cinq cents mètres. Limite de vitesse : {limit} kilomètres par heure.",
    ai_tools: "Outils Pro",
    legal_assistant: "Défense Juridique",
    generate_defense: "Générer Requête",
    vigilante_chat: "Chatter avec Vigilante",
    chat_placeholder: "Posez une question sur le trafic ou les amendes...",
    generating: "Génération du document...",
    defense_ready: "Requête Générée",
    ask_vigilante: "Demander au Vigilante",
    upload_pdf: "Joindre Notification (PDF)",
    pdf_size_error: "Le fichier PDF est trop volumineux. Maximum 500 Ko.",
    pdf_type_error: "Seuls les fichiers PDF sont autorisés.",
    file_attached: "Document joint : {name}"
  },
  de: {
    dashboard: "Dashboard",
    map: "Intelligenzkarte",
    community: "Community-Feed",
    myReports: "Meine Berichte",
    settings: "Einstellungen",
    logout: "Abmelden",
    logout_confirm_title: "Abmelden?",
    logout_confirm_msg: "Sind Sie sicher, dass Sie das Überwachungssystem verlassen möchten?",
    confirm_yes: "Ja, Abmelden",
    confirm_no: "Abbrechen",
    login: "Google Login",
    welcome: "Willkommen, Agent",
    stats_total: "Gesamtberichte",
    stats_impact: "Soziale Auswirkung",
    stats_score: "Bürger-Punktestand",
    report_incident: "Vorfall Melden",
    description_placeholder: "Was ist passiert? Beschreiben Sie das Problem...",
    add_photo: "Foto Hinzufügen",
    change_photo: "Foto Ändern",
    location_set: "Standort Festgelegt",
    select_location: "Auf Karte Auswählen",
    submit_report: "Bericht Senden",
    processing: "Verarbeitung...",
    location_required: "Bitte wählen Sie einen Ort auf der Karte aus",
    settings_account: "Agentenprofil",
    settings_system: "Systempräferenzen",
    settings_voice: "Sprachwarnungen",
    settings_theme: "Visuelles Thema",
    settings_lang: "Systemsprache",
    settings_personalize: "Personalisierung",
    username_label: "Agentenname",
    bio_label: "Bio/Status",
    save_changes: "Speichern",
    gdpr_title: "Datenschutz & DSGVO",
    gdpr_desc: "Verwalten Sie Ihre persönlichen Daten gemäß den europäischen Datenschutzstandards.",
    gdpr_export: "Meine Daten Exportieren (JSON)",
    gdpr_delete: "Konto & Daten Löschen",
    gdpr_delete_warn: "Diese Aktion ist unwiderruflich.",
    severity_label: "Schweregrad",
    ai_analysis_label: "KI-Analyse",
    pdf_report_btn: "PDF-BERICHT",
    level_label: "Stufe",
    activity_pulse: "Aktivitätspuls",
    recent_milestones: "Jüngste Erfolge",
    select_target_msg: "WÄHLEN SIE DEN ORT DES VORFALLLS AUF DER KARTE AUS",
    voice_alert_text: "Achtung. Neuer Vorfall ({category}) mit Schweregrad {severity}. Zusammenfassung: {summary}.",
    navigation: "Navigation",
    start_point: "Startpunkt",
    end_point: "Ziel",
    get_directions: "Route Planen",
    clear_route: "Route Olschen",
    my_location: "Mein Standort",
    route_info: "Reiseinfo",
    show_radars: "Radare anzeigen",
    radar_limit: "Tempolimit",
    radar_type: "Radartyp",
    radar_fixed: "Fest",
    radar_alert_voice: "Achtung. Stationärer Blitzer in fünfhundert Metern. Geschwindigkeitsbegrenzung: {limit} Kilometer pro Stunde.",
    ai_tools: "Pro-Tools",
    legal_assistant: "Rechtliche Verteidigung",
    generate_defense: "Anforderung generieren",
    vigilante_chat: "Mit Vigilante chatten",
    chat_placeholder: "Fragen Sie etwas über Verkehr oder Bußgelder...",
    generating: "Dokument wird generiert...",
    defense_ready: "Anforderung generiert",
    ask_vigilante: "Vigilante fragen",
    upload_pdf: "Bescheid anhängen (PDF)",
    pdf_size_error: "PDF-Datei ist zu groß. Maximal 500 KB.",
    pdf_type_error: "Nur PDF-Dateien sind erlaubt.",
    file_attached: "Dokument angehängt: {name}"
  }
};